---
server_hostname: metrics
server_mounted_volumes:
  - /mnt/metrics_data

prometheus_data_dir: /mnt/metrics_data/prometheus

# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
prometheus_config: |
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: metrics_prometheus
      scheme: https
      static_configs:
        - targets: ['metrics.sbsbx.com']
    - job_name: metrics_caddy
      scheme: https
      metrics_path: /caddy/metrics
      static_configs:
        - targets: ['metrics.sbsbx.com']
    - job_name: metrics_server
      scheme: https
      metrics_path: /server/metrics
      static_configs:
        - targets: ['metrics.sbsbx.com']
    - job_name: bloggulus_web
      scheme: https
      static_configs:
        - targets: ['bloggulus.com']
    - job_name: bloggulus_caddy
      scheme: https
      metrics_path: /caddy/metrics
      static_configs:
        - targets: ['bloggulus.com']
    - job_name: bloggulus_server
      scheme: https
      metrics_path: /server/metrics
      static_configs:
        - targets: ['bloggulus.com']
    - job_name: minecraft_server
      scheme: https
      metrics_path: /server/metrics
      static_configs:
        - targets: ['mc.sbsbx.com']

# https://caddyserver.com/docs/caddyfile
caddy_config: |
  {
    servers {
      metrics
    }
  }
  metrics.sbsbx.com {
    metrics /caddy/metrics
    handle_path /server/* {
      reverse_proxy 127.0.0.1:9100
    }
    reverse_proxy 127.0.0.1:9090
  }
