---
server_hostname: metrics
server_mounted_volumes:
  - /mnt/metrics_data

prometheus_data_retention: 90d
prometheus_data_directory: /mnt/metrics_data/prometheus

# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
prometheus_config: |
  global:
    scrape_interval: 5s
  scrape_configs:
    - job_name: metrics_prometheus
      scheme: https
      static_configs:
        - targets: ['metrics.sbsbx.com']
    - job_name: metrics_server
      scheme: https
      metrics_path: /server/metrics
      static_configs:
        - targets: ['metrics.sbsbx.com']
    - job_name: bloggulus_web
      scheme: https
      static_configs:
        - targets: ['bloggulus.com']
    - job_name: bloggulus_server
      scheme: https
      metrics_path: /server/metrics
      static_configs:
        - targets: ['bloggulus.com']
    - job_name: bloggulus_database
      scheme: https
      metrics_path: /database/metrics
      static_configs:
        - targets: ['bloggulus.com']
    - job_name: minecraft_server
      scheme: https
      metrics_path: /server/metrics
      static_configs:
        - targets: ['mc.sbsbx.com']

# https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
grafana_config: |
  [server]
  domain = metrics.sbsbx.com
  root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
  serve_from_sub_path = true

# https://caddyserver.com/docs/caddyfile
caddy_config: |
  metrics.sbsbx.com {
    handle_path /server/* {
      reverse_proxy 127.0.0.1:9100
    }
    reverse_proxy /grafana* 127.0.0.1:3000
    reverse_proxy 127.0.0.1:9090
  }
