---
server_hostname: sbsbx
server_internal_network_ip: 10.136.0.4
server_internal_network_cidr: 10.136.0.0/16
server_mounted_volumes:
  - /mnt/sbsbx_data

victoria_metrics_data_dir: /mnt/sbsbx_data/victoria_metrics
victoria_logs_data_dir: /mnt/sbsbx_data/victoria_logs
victoria_traces_data_dir: /mnt/sbsbx_data/victoria_traces

grafana_config: |
  [server]
  http_addr = 127.0.0.1
  http_port = 3000
  root_url = https://melt.sbsbx.com

caddy_config: |
  {
    servers {
      timeouts {
        read_body   10s
        read_header 5s
        write       30s
        idle        5m
      }
    }
  }
  www.melt.sbsbx.com {
    redir https://melt.sbsbx.com{uri} permanent
  }
  melt.sbsbx.com {
    reverse_proxy 127.0.0.1:3000
  }
