---

- name: Install postgresql (and psycopg2)
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
      - python3-psycopg2
    update_cache: yes
  become: yes
  become_user: root

- name: Setup postgresql.conf settings
  lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^#?data_directory"
      line: "data_directory={{ postgresql_data_directory }}"
  notify: restart postgresql
  become: yes
  become_user: root

- name: Create cluster users
  postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ postgresql_users }}"
  no_log: yes
  become: yes
  become_user: postgres

- name: Create cluster databases
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
  with_items: "{{ postgresql_databases }}"
  become: yes
  become_user: postgres
