---

# TODO: auto-adjust config based on system memory
# https://www.enterprisedb.com/postgres-tutorials/how-tune-postgresql-memory
# https://pgtune.leopard.in.ua/

- name: Install postgresql (and psycopg2)
  apt:
    name:
      - postgresql-12
      - postgresql-client-12
      - python3-psycopg2
    update_cache: yes
  become: yes
  become_user: root

- name: Create cluster users
  postgresql_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ postgresql_users }}"
  no_log: yes
  become: yes
  become_user: postgres

- name: Create cluster databases
  postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
  with_items: "{{ postgresql_databases }}"
  become: yes
  become_user: postgres
