---
- name: Enable overcommit_memory in sysctl
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: 1
  become: true
  become_user: root

- name: Setup redis apt repo key
  ansible.builtin.apt_key:
    url: https://packages.redis.io/gpg
  become: true
  become_user: root

- name: Setup redis apt repo
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://packages.redis.io/deb {{ ansible_distribution_release }} main"
  become: true
  become_user: root

- name: Install redis
  ansible.builtin.apt:
    name: redis
    update_cache: true
  become: true
  become_user: root

- name: Configure maxmemory
  ansible.builtin.lineinfile:
    path: "/etc/redis/redis.conf"
    regexp: "^(# )?maxmemory "
    line: "maxmemory {{ redis_maxmemory }}"
  notify: restart redis
  become: true
  become_user: root

- name: Configure maxmemory-policy
  ansible.builtin.lineinfile:
    path: "/etc/redis/redis.conf"
    regexp: "^(# )?maxmemory-policy "
    line: "maxmemory-policy {{ redis_maxmemory_policy }}"
  notify: restart redis
  become: true
  become_user: root

- name: Start and enable redis
  ansible.builtin.systemd_service:
    name: redis-server
    state: started
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
