---

- name: Install grafana-agent
  apt:
    deb: https://github.com/grafana/agent/releases/download/v{{ agent_version }}/grafana-agent-{{ agent_version }}-1.{{ agent_architecture }}.deb
    update_cache: yes
  become: yes
  become_user: root

- name: Add grafana-agent to journal groups
  user:
    name: grafana-agent
    groups: adm,systemd-journal
    append: yes
  notify: restart grafana-agent
  become: yes
  become_user: root

- name: Setup grafana-agent config file
  template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
    mode: "0640"
    owner: root
    group: grafana-agent
  notify: restart grafana-agent
  become: yes
  become_user: root

- name: Start and enable grafana-agent
  systemd:
    name: grafana-agent
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
