---

- name: Install grafana-agent
  apt:
    deb: https://github.com/grafana/agent/releases/download/v{{ grafana_version }}/grafana-agent-{{ grafana_version }}-1.amd64.deb
    update_cache: yes
  become: yes
  become_user: root

- name: Setup grafana-agent config file
  template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
    mode: "0640"
    owner: root
    group: grafana-agent
  notify: restart grafana-agent
  become: yes
  become_user: root
