---

- name: Create the application user
  user:
    name: "{{ web_app_user }}"
    shell: /bin/bash
  become: yes
  become_user: root

- name: Setup authorized SSH public key for GitHub Actions
  authorized_key:
    user: "{{ web_app_user }}"
    key: "{{ web_app_deployment_key }}"
  become: yes
  become_user: "{{ web_app_user }}"

- name: Setup application config file
  copy:
    content: "{{ web_app_config }}"
    dest: /etc/{{ web_app_name }}.conf
    owner: root
    group: "{{ web_app_user }}"
    mode: "0640"
  become: yes
  become_user: root

- name: Setup systemd service file
  template:
    src: web_app.service.j2
    dest: /etc/systemd/system/{{ web_app_name }}.service
    mode: "0644"
  notify: restart web app
  become: yes
  become_user: root

- name: Allow app user to control its application
  lineinfile:
    path: /etc/sudoers
    line: "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl {{ item }} {{ web_app_name }}"
    validate: "visudo -cf %s"
  with_items:
    - status
    - start
    - restart
    - reload
  become: yes
  become_user: root

- name: Enable application at startup
  systemd:
    name: "{{ web_app_name }}"
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
