---

- hosts: bloggulus
  roles:
    - server
    - agent
    - vpc

- hosts: bloggulus_db
  roles:
    - postgresql
    - pg2s3

- hosts: bloggulus_web
  roles:
    - redis
    - caddy
    - web_app_v2
