---

# TODO: peer fails to start because the transactor has a delayed startup
- name: restart datomic
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  with_items:
    - datomic-transactor
    - datomic-peer
  become: yes
  become_user: root
