---

- name: reload caddy
  systemd:
    name: caddy
    state: reloaded
    daemon_reload: yes
  become: yes
  become_user: root

- name: restart web app
  systemd:
    name: "{{ web_app_name }}-{{ item }}"
    state: restarted
    daemon_reload: yes
  with_items: "{{ web_app_components }}"
  become: yes
  become_user: root
