---

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - debian-archive-keyring
      - debian-keyring
    update_cache: yes
  become: yes
  become_user: root

- name: Setup caddy apt repo key
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
  become: yes
  become_user: root

- name: Setup caddy apt repo
  apt_repository:
    repo: "{{ item }}"
    update_cache: no
  with_items:
    - "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    - "deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
  become: yes
  become_user: root

- name: Install caddy
  apt:
    name: caddy
    update_cache: yes
  become: yes
  become_user: root

- name: Setup caddy config file
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0640"
    owner: root
    group: caddy
  when: caddy_config
  notify: reload caddy
  become: yes
  become_user: root

- name: Setup firewall rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  with_items:
    - rule: allow
      port: 80
    - rule: allow
      port: 443
  become: yes
  become_user: root

- name: Start and enable caddy
  systemd:
    name: caddy
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
