---

- name: Setup caddy apt repo key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
  become: true
  become_user: root

- name: Setup caddy apt repo
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    - "deb-src https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
  become: true
  become_user: root

- name: Install caddy
  ansible.builtin.apt:
    name: caddy
    update_cache: true
  become: true
  become_user: root

- name: Setup caddy config file
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    mode: "0640"
    owner: root
    group: caddy
  when: caddy_config is truthy
  notify: reload caddy
  become: true
  become_user: root

- name: Setup firewall rules
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
  with_items:
    - rule: allow
      port: 80
    - rule: allow
      port: 443
  become: true
  become_user: root

- name: Start and enable caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: started
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
