---

# list of dicts with keys: rule, port
#
# example:
#   - rule: allow
#     port: 80
#   - rule: allow
#     port: 443
firewall_rules: []

# (VPC) network CIDR range
vpc_network_prefix: ~

# (VPC) private IP of gateway node
vpc_gateway_private_ip: ~

# (VPC) host var indicating gateway node
vpc_is_gateway: no

# (VPC) host var indicating internal nodes
vpc_is_internal: no
