---

- name: Install php dependencies
  apt:
    name:
      - php-curl
      - php-fpm
      - php-gd
      - php-imagick
      - php-intl
      - php-mbstring
      - php-mysql
      - php-redis
      - php-soap
      - php-xml
      - php-xmlrpc
      - php-zip
    update_cache: yes
  become: yes
  become_user: root

- name: Create directory for wordpress files
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    state: directory
  become: yes
  become_user: root

- name: Check if wordpress is installed
  stat:
    path: "/var/www/wordpress/wp-config-sample.php"
  register: wp_config_sample
  become: yes
  become_user: root

- name: Download and extract wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www
    remote_src: yes
  when: not wp_config_sample.stat.exists
  become: yes
  become_user: root

- name: Update ownership of wordpress files
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    recurse: yes
  become: yes
  become_user: root

- name: Setup initial wordpress config file
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    mode: "0600"
    owner: www-data
    group: www-data
  when: wordpress_config and (not wp_config_sample.stat.exists)
  become: yes
  become_user: root

- name: Download and setup adminer
  get_url:
    url: https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php
    dest: /var/www/wordpress/adminer.php
    mode: "0644"
    owner: www-data
    group: www-data
  become: yes
  become_user: root
