- name: Setup nodejs apt repo key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
  become: yes
  become_user: root

- name: Setup nodejs apt repo
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_major_version }}.x nodistro main"
  become: yes
  become_user: root

- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
  become: yes
  become_user: root