---
- name: Create mfd group
  ansible.builtin.group:
    name: mfd
    system: true
  become: true
  become_user: root

- name: Create mfd user
  ansible.builtin.user:
    name: mfd
    group: mfd
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  become: true
  become_user: root

- name: Add admin users to the mfd group
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: mfd
    append: true
  with_items: "{{ server_admin_users }}"
  become: true
  become_user: root

- name: Install mfd (latest)
  ansible.builtin.apt:
    deb: https://github.com/theandrew168/mfd/releases/latest/download/mfd_{{ mfd_os }}_{{ mfd_arch }}.deb
    update_cache: true
  when: mfd_version == "latest"
  become: true
  become_user: root

- name: Install mfd (version)
  ansible.builtin.apt:
    deb: https://github.com/theandrew168/mfd/releases/download/v{{ mfd_version }}/mfd_{{ mfd_os }}_{{ mfd_arch }}.deb
    update_cache: true
  when: mfd_version != "latest"
  become: true
  become_user: root

- name: Create mfd config directory
  ansible.builtin.file:
    path: "{{ mfd_config_path | dirname }}"
    state: directory
    owner: mfd
    group: mfd
    mode: "0750"
  become: true
  become_user: root

- name: Setup mfd config file
  ansible.builtin.copy:
    content: "{{ mfd_config }}"
    dest: "{{ mfd_config_path }}"
    mode: "0600"
    owner: mfd
    group: mfd
  become: true
  become_user: root

- name: Deploy the application
  ansible.builtin.command: mfd deploy
  args:
    chdir: "{{ mfd_config_path | dirname }}"
    creates: "{{ mfd_config_path | dirname }}/active"
  become: true
  become_user: root
