---
# version of victoria metrics to install
victoria_metrics_version: v1.149.0

# directory to hold victoria metrics data
# NOTE: don't use a mount point directly: use a subdir
victoria_metrics_data_dir: ~
