---
- name: Create node_exporter group
  group:
    name: node_exporter
    system: true
  become: yes
  become_user: root

- name: Create node_exporter user
  user:
    name: node_exporter
    group: node_exporter
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  become: yes
  become_user: root

- name: Download and extract node_exporter
  unarchive:
    remote_src: yes
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_os }}-{{ node_exporter_arch }}.tar.gz
    dest: /tmp
    creates: /tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_os }}-{{ node_exporter_arch }}/node_exporter
    owner: root
    group: root
  become: yes
  become_user: root

- name: Copy node_exporter binary
  copy:
    remote_src: yes
    src: /tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_os }}-{{ node_exporter_arch }}/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: "0755"
    owner: root
    group: root
  notify: restart node_exporter
  become: yes
  become_user: root

- name: Create node_exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"
    owner: root
    group: root
  notify: restart node_exporter
  become: yes
  become_user: root

- name: Start and enable node_exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
