---

- name: Install jamql (latest)
  apt:
    deb: https://github.com/theandrew168/jamql/releases/latest/download/jamql_{{ jamql_os }}_{{ jamql_arch }}.deb
    update_cache: yes
  when: jamql_version == "latest"
  notify: restart jamql
  become: yes
  become_user: root

- name: Install jamql (version)
  apt:
    deb: https://github.com/theandrew168/jamql/releases/download/v{{ jamql_version }}/jamql_{{ jamql_os }}_{{ jamql_arch }}.deb
    update_cache: yes
  when: jamql_version != "latest"
  notify: restart jamql
  become: yes
  become_user: root

- name: Setup jamql config file
  copy:
    content: "{{ jamql_config }}"
    dest: /etc/jamql.conf
    mode: "0640"
    owner: root
    group: jamql
  notify: restart jamql
  become: yes
  become_user: root

- name: Start and enable jamql
  systemd:
    name: jamql
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
