- name: Set hostname (transient)
  hostname:
    name: "{{ server_hostname }}"
  when: server_hostname
  become: yes
  become_user: root

- name: Set hostname (/etc/hosts)
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"
  when: server_hostname
  become: yes
  become_user: root

- name: Set hostname (/etc/hostname)
  template:
    src: hostname.j2
    dest: /etc/hostname
    mode: "0644"
  when: server_hostname
  become: yes
  become_user: root
