- name: Ensure en_US.UTF-8 locale is available
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present
  become: true
  become_user: root

- name: Check current system locale
  ansible.builtin.command:
    cmd: localectl status
  register: locale_status
  changed_when: false
  become: true
  become_user: root

- name: Set system locale
  ansible.builtin.command:
    cmd: localectl set-locale en_US.UTF-8
  when: "'LANG=en_US.UTF-8' not in locale_status.stdout"
  become: true
  become_user: root

- name: Set timezone to Etc/UTC
  community.general.timezone:
    name: Etc/UTC
  become: true
  become_user: root
