---
- name: Ensure at least one admin user is configured
  fail:
    msg: At least one admin user must be configured
  when: not server_admin_users

- name: Upgrade base packages
  apt:
    upgrade: yes
    update_cache: yes
  when: ansible_ssh_user == "root"
  become: yes
  become_user: root

- include_tasks: auth.yml

- name: Ensure a non-root ansible user is being used
  fail:
    msg: Only non-root ansible users can proceed
  when: ansible_ssh_user == "root"

- include_tasks: hostname.yml

- include_tasks: locale.yml

- include_tasks: systemd.yml

- include_tasks: volumes.yml

- include_tasks: swap.yml

- include_tasks: packages.yml

- name: Make vim the default text editor :)
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  become: yes
  become_user: root
