- name: Create swapfile
  command:
    cmd: fallocate -l 1G /swapfile
    creates: /swapfile
  register: create_swapfile
  become: yes
  become_user: root

- name: Set swapfile permissions
  file:
    path: /swapfile
    mode: 0600
  become: yes
  become_user: root

- name: Initialize swapfile
  command:
    cmd: mkswap /swapfile
  when: create_swapfile is changed
  become: yes
  become_user: root

- name: Enable swapfile
  command:
    cmd: swapon /swapfile
  when: create_swapfile is changed
  become: yes
  become_user: root

- name: Add swapfile to fstab
  mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present
  become: yes
  become_user: root

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: 10
  become: yes
  become_user: root

- name: Configure vfs_cache_pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: 50
  become: yes
  become_user: root
