- name: Limit journald log sizes
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?{{ item.name }}"
    line: "{{ item.name }}={{ item.value }}"
  with_items:
    - name: SystemMaxUse
      value: 1G
  notify: restart systemd-journald
  become: yes
  become_user: root
