---
- name: Create bloggulus group
  group:
    name: bloggulus
    system: true
  become: yes
  become_user: root

- name: Create bloggulus user
  user:
    name: bloggulus
    group: bloggulus
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  become: yes
  become_user: root

- name: Setup bloggulus config file
  copy:
    content: "{{ bloggulus_config }}"
    dest: /etc/bloggulus.conf
    mode: "0640"
    owner: root
    group: bloggulus
  notify: restart bloggulus
  become: yes
  become_user: root

- name: Create bloggulus systemd service
  template:
    src: bloggulus.service.j2
    dest: /etc/systemd/system/bloggulus.service
    mode: "0644"
    owner: root
    group: root
  notify: restart bloggulus
  become: yes
  become_user: root

- name: Start and enable bloggulus.service
  systemd:
    name: bloggulus.service
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root

- name: Create bloggulus systemd socket
  template:
    src: bloggulus.socket.j2
    dest: /etc/systemd/system/bloggulus.socket
    mode: "0644"
    owner: root
    group: root
  notify: restart bloggulus
  become: yes
  become_user: root

- name: Start and enable bloggulus.socket
  systemd:
    name: bloggulus.socket
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root