---
- name: Create bloggulus group
  ansible.builtin.group:
    name: bloggulus
    system: true
  become: true
  become_user: root

- name: Create bloggulus user
  ansible.builtin.user:
    name: bloggulus
    group: bloggulus
    shell: /usr/sbin/nologin
    system: true
    create_home: false
  become: true
  become_user: root

- name: Add bloggulus user to the mfd group
  ansible.builtin.user:
    name: bloggulus
    groups: mfd
    append: true
  become: true
  become_user: root

- name: Add bloggulus user to the dbuser group
  ansible.builtin.user:
    name: bloggulus
    groups: dbuser
    append: true
  when: postgresql_unix_domain_socket_only
  become: true
  become_user: root

- name: Setup bloggulus config file
  ansible.builtin.copy:
    content: "{{ bloggulus_config }}"
    dest: /etc/bloggulus.conf
    mode: "0640"
    owner: root
    group: bloggulus
  notify: restart bloggulus
  become: true
  become_user: root

- name: Create bloggulus systemd service
  ansible.builtin.template:
    src: bloggulus.service.j2
    dest: /etc/systemd/system/bloggulus.service
    mode: "0644"
    owner: root
    group: root
  notify: restart bloggulus
  become: true
  become_user: root

- name: Create bloggulus systemd socket
  ansible.builtin.template:
    src: bloggulus.socket.j2
    dest: /etc/systemd/system/bloggulus.socket
    mode: "0644"
    owner: root
    group: root
  notify: restart bloggulus
  become: true
  become_user: root

- name: Start and enable bloggulus.socket
  ansible.builtin.systemd_service:
    name: bloggulus.socket
    state: started
    enabled: true
    daemon_reload: true
  become: true
  become_user: root

- name: Start and enable bloggulus.service
  ansible.builtin.systemd_service:
    name: bloggulus.service
    state: started
    enabled: true
    daemon_reload: true
  become: true
  become_user: root
