---

# directory to hold postgresql data
# NOTE: don't use a mount point directly: use a subdir
postgresql_data_directory: ~

# list of dicts with keys: username, password
#
# example:
#   - username: postgres
#     password: postgres
postgresql_users: []

# list of dicts with keys: name, owner
#
# example:
#   - name: foobar
#     owner: postgres
postgresql_databases: []
