---

# postgresql version (not really customizable)
postgresql_version: 16

# postgresql bin directory (not really customizable)
postgresql_bin_dir: /usr/lib/postgresql/{{ postgresql_version }}/bin

# postgresql conf directory (not really customizable)
postgresql_conf_dir: /etc/postgresql/{{ postgresql_version }}/main

# directory to hold postgresql data
# NOTE: don't use a mount point directly: use a subdir
postgresql_data_dir: ~

# server private network IP (if applicable)
postgresql_private_network_ip: ~

# server private network CIDR (if applicable)
postgresql_private_network_cidr: ~

# database tuning params based on:
# https://pgtune.leopard.in.ua/
postgresql_tuning_parameters: []

# list of dicts with keys: username, password
postgresql_users: []
#  - username: postgres
#    password: postgres

# list of dicts with keys: name, owner
postgresql_databases: []
#  - name: foobar
#    owner: postgres

# list of extensions to enable
postgresql_extensions:
  - pg_stat_statements
