---

# directory to hold postgresql data
# NOTE: don't use a mount point directly: use a subdir
postgresql_data_directory: ~

# server private network IP (if applicable)
postgresql_private_network_ip: ~

# server private network CIDR (if applicable)
postgresql_private_network_cidr: ~

# database tuning params based on:
# https://pgtune.leopard.in.ua/
postgresql_tuning_parameters: []

# list of dicts with keys: username, password
postgresql_users: []
#  - username: postgres
#    password: postgres

# list of dicts with keys: name, owner
postgresql_databases: []
#  - name: foobar
#    owner: postgres

# list of extensions to enable
postgresql_extensions:
  - pg_stat_statements
