---

# directory to hold postgresql data
postgresql_data_directory: /var/lib/postgresql/12/main

# list of dicts with keys: username, password
#
# example:
#   - username: postgres
#     password: postgres
postgresql_users: []

# list of dicts with keys: name, owner
#
# example:
#   - name: foobar
#     owner: postgres
postgresql_databases: []
