---

# directory to hold postgresql data
# NOTE: don't use a mount point directly: use a subdir
postgresql_data_directory: ~

# addresses to listen for incoming connections
# NOTE: this will usually be "localhost" plus a private network IP
postgresql_listen_addresses: []

# extra entries to add the pg_hba.conf file
# NOTE: this can be used to further enforce a private network
postgresql_extra_hba_entries: []

# database tuning params based on:
# https://pgtune.leopard.in.ua/
postgresql_tuning_parameters: []

# list of dicts with keys: username, password
postgresql_users: []
#  - username: postgres
#    password: postgres

# list of dicts with keys: name, owner
postgresql_databases: []
#  - name: foobar
#    owner: postgres
