---

- name: Install java
  apt:
    name:
      - openjdk-8-jre-headless
    update_cache: yes
  when: web_app_is_jar
  become: yes
  become_user: root

- name: Create the application user
  user:
    name: "{{ web_app_user }}"
    shell: /bin/bash
  become: yes
  become_user: root

- name: Setup authorized SSH public key for GitHub Actions
  authorized_key:
    user: "{{ web_app_user }}"
    key: "{{ web_app_deployment_key }}"
  become: yes
  become_user: "{{ web_app_user }}"

- name: Create application config directory
  file:
    path: /etc/{{ web_app_name }}
    mode: "0755"
    state: directory
  become: yes
  become_user: root

- name: Setup systemd environment vars file
  template:
    src: web_app.env.j2
    dest: /etc/{{ web_app_name }}/{{ web_app_name }}.env
    mode: "0600"
  notify: restart web app
  no_log: yes
  become: yes
  become_user: root

- name: Setup export environment vars file
  template:
    src: web_app.exp.j2
    dest: /etc/{{ web_app_name }}/{{ web_app_name }}.exp
    mode: "0600"
  notify: restart web app
  no_log: yes
  become: yes
  become_user: root

- name: Setup systemd service file
  template:
    src: web_app.service.j2
    dest: /etc/systemd/system/{{ web_app_name }}.service
    mode: "0644"
  notify: restart web app
  become: yes
  become_user: root

- name: Allow app user to control its application
  lineinfile:
    path: /etc/sudoers
    line: "{{ web_app_user }} ALL=NOPASSWD: /bin/systemctl {{ item }} {{ web_app_name }}"
    validate: "visudo -cf %s"
  with_items:
    - status
    - start
    - restart
    - reload
  become: yes
  become_user: root

- name: Enable application at startup
  systemd:
    name: "{{ web_app_name }}"
    enabled: yes
    daemon_reload: yes
  become: yes
  become_user: root
