---
# version to install
prometheus_version: 2.45.3

# target operating system
prometheus_os: linux

# target architecture
prometheus_arch: amd64

# metrics data directory
prometheus_data_dir: ~

# config file contents
prometheus_config: ~
